[versions]

compileSdk = "36"
targetSdk = "35"
java = "17"

agp = "8.11.2"
kotlin = "2.2.0"
ksp = "2.2.0-1.0.26"
ktfmt = "0.25.0"

coroutines = "1.10.2"
kotlinxUuid = "0.0.20"
kotlinxSerializationJson = "1.10.0"
kotlinReflect = "2.3.20"
collection = "1.5.0"

desugar_jdk_libs = "2.1.5"

coreKtx = "1.17.0"
androidxAppcompat = "1.7.0"
androidxAnnotation = "1.9.1"
datastoreCore = "1.2.0"
androidxCoreSplashscreen = "1.0.1"
material = "1.13.0"
materialKolor = "4.1.1"
palette = "1.0.0"

composeBom = "2026.02.01"
foundation = "1.10.4"
foundationLayout = "1.10.4"
uiText = "1.10.4"
activityCompose = "1.12.4"
navigationCompose = "2.9.7"
runtime = "1.10.4"

material3 = "1.4.0"
composeIcons = "1.1.1"
animation = "1.10.4"
materialIcons = "1.7.8"
materialIconsExtended = "1.7.8"

lifecycleRuntimeKtx = "2.10.0"

hilt = "2.51.1"
androidxHiltNavigationCompose = "1.2.0"

aboutlibrariesCompose = "13.2.1"
aboutlibraries = "13.2.1"
accompanist = "0.36.0"
utilcode = "1.31.1"

coilCompose = "2.7.0"
coilSvg = "2.7.0"

gson = "2.13.2"

jgit = "7.3.0.202506031305-r"
jgitSshApache = "7.5.0.202512021534-r"
lsp4j = "0.24.0"
zipalignJava = "1.2.2"

editor = "0.23.6"
android-tree-sitter = "4.3.2"
tree-sitter-aidl = "4.3.2"
tree-sitter-java = "4.3.2"
tree-sitter-json = "4.3.2"
tree-sitter-kotlin = "4.3.2"
tree-sitter-log = "4.3.2"
tree-sitter-properties = "4.3.2"
tree-sitter-python = "4.3.2"
tree-sitter-xml = "4.3.2"

commonsCompress = "1.26.1"
commonsNet = "3.13.0"
okhttp = "4.12.0"
nanohttpd = "2.3.1"
xzJava = "1.9"

anrwatchdog = "1.4.0"
photoview = "2.3.0"
runner = "1.7.0"
composeDnd = "0.4.0"
androidsvgAar = "1.4"
joni = "2.2.7"
snakeyaml = "3.0.1"
documentfile = "1.1.0"
glide = "5.0.5"
materialIconsCore = "1.7.8"
activity = "1.12.0"
quickjsAndroid = "0.9.2"
coil = "2.7.0"
ec4jCore = "1.2.0"
jcodings = "1.0.64"
jdtAnnotation = "2.4.100"
kotlinxCoroutines = "1.10.2"
moshi = "1.15.2"
regexOnig = "1.0.3"
regexRe2j = "1.0.2"
motionCompose = "2.0.1"

[libraries]
androidx-activity = { module = "androidx.activity:activity", version.ref = "activity" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidxAnnotation" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppcompat" }
androidx-collection = { module = "androidx.collection:collection", version = "1.5.0" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidxCoreSplashscreen" }
androidx-datastore-core = { module = "androidx.datastore:datastore-core", version.ref = "datastoreCore" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastoreCore" }
androidx-desugar = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
androidx-documentfile = { module = "androidx.documentfile:documentfile", version.ref = "documentfile" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-palette = { group = "androidx.palette", name = "palette", version.ref = "palette" }

androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "foundation" }
androidx-compose-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout", version.ref = "foundationLayout" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-text = { group = "androidx.compose.ui", name = "ui-text", version.ref = "uiText" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
androidx-compose-animation = { group = "androidx.compose.animation", name = "animation", version.ref = "animation" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "runtime" }

# Dependency Injection
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidxHiltNavigationCompose" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
hilt-android-gradle-plugin = { group = "com.google.dagger", name = "hilt-android-gradle-plugin", version.ref = "hilt" }

# Asynchrony & Utilities
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-uuid = { group = "app.softwork", name = "kotlinx-uuid-core", version.ref = "kotlinxUuid" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlinReflect" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }

# Editor & Git
sora-editor = { module = "io.github.Rosemoe.sora-editor:editor", version.ref = "editor" }
sora-editor-lsp = { module = "io.github.Rosemoe.sora-editor:editor-lsp", version.ref = "editor" }
sora-language-textmate = { module = "io.github.Rosemoe.sora-editor:language-textmate", version.ref = "editor" }
sora-language-treesitter = { module = "io.github.Rosemoe.sora-editor:language-treesitter", version.ref = "editor" }
sora-language-java = { group = "io.github.rosemoe.sora-editor", name = "language-java", version.ref = "editor" }

# tree-sitter
android-tree-sitter = { module = "com.itsaky.androidide.treesitter:android-tree-sitter", version.ref = "android-tree-sitter" }
tree-sitter-aidl = { module = "com.itsaky.androidide.treesitter:tree-sitter-aidl", version.ref = "tree-sitter-aidl" }
tree-sitter-java = { module = "com.itsaky.androidide.treesitter:tree-sitter-java", version.ref = "tree-sitter-java" }
tree-sitter-json = { module = "com.itsaky.androidide.treesitter:tree-sitter-json", version.ref = "tree-sitter-json" }
tree-sitter-kotlin = { module = "com.itsaky.androidide.treesitter:tree-sitter-kotlin", version.ref = "tree-sitter-kotlin" }
tree-sitter-log = { module = "com.itsaky.androidide.treesitter:tree-sitter-log", version.ref = "tree-sitter-log" }
tree-sitter-properties = { module = "com.itsaky.androidide.treesitter:tree-sitter-properties", version.ref = "tree-sitter-properties" }
tree-sitter-python = { module = "com.itsaky.androidide.treesitter:tree-sitter-python", version.ref = "tree-sitter-python" }
tree-sitter-xml = { module = "com.itsaky.androidide.treesitter:tree-sitter-xml", version.ref = "tree-sitter-xml" }

# Netzwerk & Kompression
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
nanohttpd = { module = "org.nanohttpd:nanohttpd", version.ref = "nanohttpd" }
commons-net = { module = "commons-net:commons-net", version.ref = "commonsNet" }
commons-compress = { group = "org.apache.commons", name = "commons-compress", version.ref = "commonsCompress" }
xz-java = { group = "org.tukaani", name = "xz", version.ref = "xzJava" }

# Images
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
coil-svg = { module = "io.coil-kt:coil-svg", version.ref = "coil" }

# Misc
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
material-kolor = { module = "com.materialkolor:material-kolor", version.ref = "materialKolor" }
photoview = { module = "com.github.chrisbanes:PhotoView", version.ref = "photoview" }
quickjs-android = { module = "app.cash.quickjs:quickjs-android", version.ref = "quickjsAndroid" }
lsp4j = { module = "org.eclipse.lsp4j:org.eclipse.lsp4j", version.ref = "lsp4j" }
jgit = { module = "org.eclipse.jgit:org.eclipse.jgit", version.ref = "jgit" }
jgit-ssh-apache = { module = "org.eclipse.jgit:org.eclipse.jgit.ssh.apache", version.ref = "jgitSshApache" }
jcodings = { module = "org.jruby.jcodings:jcodings", version.ref = "jcodings" }
joni = { module = "org.jruby.joni:joni", version.ref = "joni" }
snakeyaml-engine = { module = "org.snakeyaml:snakeyaml-engine", version.ref = "snakeyaml" }
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
androidsvg-aar = { module = "com.caverock:androidsvg-aar", version.ref = "androidsvgAar" }
ec4j-core = { module = "org.ec4j.core:ec4j-core", version.ref = "ec4jCore" }
jdt-annotation = { module = "org.eclipse.jdt:org.eclipse.jdt.annotation", version.ref = "jdtAnnotation" }
anrwatchdog = { module = "com.github.anrwatchdog:anrwatchdog", version.ref = "anrwatchdog" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
utilcode = { group = "com.blankj", name = "utilcodex", version.ref = "utilcode" }
zipalign-java = { module = "com.github.iyxan23:zipalign-java", version.ref = "zipalignJava" }
aboutlibraries-compose = { module = "com.mikepenz:aboutlibraries-compose", version.ref = "aboutlibrariesCompose" }
accompanist-navigation-animation = { module = "com.google.accompanist:accompanist-navigation-animation", version.ref = "accompanist" }
accompanist-systemuicontroller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanist" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ktfmt = { id = "com.ncorti.ktfmt.gradle", version.ref = "ktfmt" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
aboutlibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutlibraries" }
